version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: appdaf
      DB_USER: appdaf
      DB_PASSWORD: appdaf

  nginx:
    image: nginx:alpine
    ports:
      - "9080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: appdaf
      POSTGRES_USER: appdaf
      POSTGRES_PASSWORD: appdaf
    ports:
      - "56433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
